claws-mail 3.16.0-4: 	* Makefile improvements, support for custom names (self download packages) 	* streamlined postinst.in 	* moved and modified: package_download.sh.in to product_downloader.sh.in 	* adjusted name for $Installer$ 	* Update psdetail -> v0.1.9.0dev

diff --git a/SRC/OPSI/postinst.in b/SRC/OPSI/postinst.in
--- a/SRC/OPSI/postinst.in
+++ b/SRC/OPSI/postinst.in
@@ -12,18 +12,9 @@
 #   PRODUCT_ID: id of the current product
 #   CLIENT_DATA_DIR: directory which contains the installed client data
 #=====================================================================
-# J. Boettge <boettge@mpi-halle.mpg.de>	2017-12-22 12:29:02 +0100
+# J. Boettge <boettge@mpi-halle.mpg.de>	2018-02-19 08:31:21 +0100
 #=====================================================================
 
-
-{{#ifdef_auto_download}}
-AUTO_DOWNLOAD="true"
-{{/ifdef_auto_download}}
-{{^ifdef_auto_download}}
-AUTO_DOWNLOAD="false"
-{{/ifdef_auto_download}}
-
-#LOGFILE=/tmp/${PRODUCT_ID}__opsi_package_install.log
 LOGFILE={{O_INST_LOG}}
 
 exec >> $LOGFILE
@@ -94,60 +85,17 @@ rm -rf $TMP_DIR
 
 
 {{^ifdef_allinc}}
-[ "${AUTO_DOWNLOAD}" != "true" ] && exit 0
-
-echo "=================================================="
-echo "Downloading required files from vendor"
-date
-echo "=================================================="
-# http://www.claws-mail.org/win32/
-# 	http://www.claws-mail.org/download.php?file=win32/claws-mail-3.16.0-1-32bit.exe
-# 	http://www.claws-mail.org/download.php?file=win32/claws-mail-3.16.0-1-64bit.exe
-
-VERSION=${PRODUCT_VERSION}
-echo "Detected version for this package: ${VERSION}"
-PROD="claws-mail"
-BUILD="1"
-
-BASE="http://www.claws-mail.org/download.php?file=win32/claws-mail-${VERSION}-${BUILD}-%%ARCH%%.exe"
-
-CNT=0
-WGET_OPTS="--max-redirect=2 --no-cookies "
-FS_THRESHOLD=10000
-
-download()
-{	
-	DL_URL=$1
-	[ -n "$2" ] && PACKAGE=$2 || PACKAGE=`basename $DL_URL`
-	
-	let "CNT++"
-	echo -e "Retrieving [$PACKAGE]\n\tfrom: [${DL_URL}]";
-	if [ -f "${DST}/${PACKAGE}" ]; then
-		echo -e "\tfile already exists"
-	else
-		eval wget ${WGET_OPTS} -nv "${DL_URL}" -O "${DST}/${PACKAGE}"
-		if  [ ! -f "${DST}/${PACKAGE}" ]; then
-			let "ERR+=1<<$CNT"
-		else
-			FILESIZE=$(stat -c%s "${DST}/${PACKAGE}")
-			if [ "${FS_THRESHOLD}" -gt "${FILESIZE}" ]; then
-				echo -e "*E*  file has an unusual size; assuming error page"
-				rm -f "${DST}/${PACKAGE}"
-				let "ERR+=1<<$CNT"
-			else			
-				chmod g+r "${DST}/${PACKAGE}"
-			fi
-		fi
-	fi	
-}
-
-
-CNT=0
-for ARCH in "32bit" "64bit"; do
-	PKG_URL=${BASE//%%ARCH%%/$ARCH}
-	PACKAGE="${PROD}_${ARCH}_${VERSION}.exe"
-	download "${PKG_URL}"  "${PACKAGE}"
-done
+{{#ifdef_auto_download}}
+### product downloader
+if [[ -f "${CLIENT_DATA_DIR}/product_downloader.sh" ]]; then
+	echo "Calling product downloader"
+	DEST_DIR=${DST} ${CLIENT_DATA_DIR}/product_downloader.sh
+	ERR=$?
+else
+	echo "Product downloader not found!"
+	ERR=2
+fi
+exit $ERR
+{{/ifdef_auto_download}}
 {{/ifdef_allinc}}
 
-exit $ERR
