claws-mail 3.17.8.1-9
* product update to 3.17.8-1
* downloader: support for curl; default is now curl
* adjusted Makefile:
	* switched from pystace to mustache (Go)
	* new target pdf (create PDF with pandoc)
	* support for *.opsifunc
* adjusted advice in control
* if `kill_running` is prohibited, `defer` instead of raising fatalError
* added Code of Conduct
* added readme.pdf
* added helpers.opsifunc v1.7
* added mustache 32/64
* added style for pandoc
* moved claws-mail.xcf out of final OPSI packages

diff --git a/SRC/CLIENT_DATA/product_downloader.sh.in b/SRC/CLIENT_DATA/product_downloader.sh.in
--- a/SRC/CLIENT_DATA/product_downloader.sh.in
+++ b/SRC/CLIENT_DATA/product_downloader.sh.in
@@ -3,23 +3,72 @@
 # Download files from vendor
 # Product: CLAWS-MAIL
 #
-# Version 1.2
-# Jens Boettge <boettge@mpi-halle.mpg.de>  2018-07-30 08:34:36 +0200
+# Version 1.3
+# Jens Boettge <boettge@mpi-halle.mpg.de>  2021-03-08 07:10:34 +0100
 #=======================================================================
 # link examples:
 # http://www.claws-mail.org/win32/
-# 	https://www.claws-mail.org/download.php?file=win32/claws-mail-3.16.0-3-32bit.exe
-# 	https://www.claws-mail.org/download.php?file=win32/claws-mail-3.16.0-3-64bit.exe
+# 	https://www.claws-mail.org/download.php?file=win32/claws-mail-3.17.8-1-32bit.exe
+# 	https://www.claws-mail.org/download.php?file=win32/claws-mail-3.17.8-1-64bit.exe
 #=======================================================================
 
 ERR=0
 THIS_DIR=$(dirname $(readlink -f $0))
+DOWNLOADER="curl"
 
-WGET=$(which wget)
-if [ -z "$WGET" ];   then echo "Error: wget not found" ;  exit 200 ; fi
 MD5EXE=$(which md5sum)
-if [ -z "$MD5EXE" ]; then echo "Error: md5sum not found"; exit 201 ; fi
+if [ -z "$MD5EXE" ]; then echo "Error: md5sum not found"; exit 200 ; fi
 
+# --- detect downloader
+case $DOWNLOADER in
+curl)
+	CURL=$(which curl)
+	if [ -z "$CURL" ]; then
+		echo "Warning: Preferred downloader CURL not found. Trying wget."
+		WGET=$(which wget)
+		if [ -z "$WGET" ]; then
+			echo "Error: WGET also not found. Giving up!"
+			exit 201
+		else
+			DOWNLOADER=wget
+		fi
+	fi
+	;;
+wget)
+	WGET=$(which wget)
+	if [ -z "$WGET" ]; then
+		echo "Warning: Preferred downloader WGET not found. Trying curl."
+		CURL=$(which curl)
+		if [ -z "$CURL" ]; then
+			echo "Error: CURL also not found. Giving up!"
+			exit 202
+		else
+			DOWNLOADER=curl
+		fi
+	fi
+	;;
+*)
+	echo "Error: none of the supported downloaders (curl, wget) was requested!"
+	exit 203
+	;;
+esac
+
+if [ "$DOWNLOADER" = "wget" ]; then
+	#options for wget:
+	DOWNLOADER=$WGET
+	DL_OPTS="--max-redirect=2 --no-cookies -nv "
+	DL_OUT="-O"
+fi
+
+if [ "$DOWNLOADER" = "curl" ]; then
+	#options for curl:
+	DOWNLOADER=$CURL
+	DL_OPTS="--silent --show-error -L "
+	DL_OUT="-o"
+fi
+
+echo "[DBG] DOWNLOADER = $DOWNLOADER"
+# ---
 
 if [ -f "${THIS_DIR}/Makefile" ] ; then
 	# Skript is running in the context of building OPSI package via make
@@ -61,7 +110,6 @@ DEST_DIR=${DEST_DIR%\/}
 
 MD5SUMS="${PROD}.md5sums"
 CNT=0
-WGET_OPTS="--max-redirect=2 --no-cookies "
 FS_THRESHOLD=10000
 
 calc_md5()
@@ -108,7 +156,7 @@ download()
         if [ -f "${DEST_DIR}/${PACKAGE}" ]; then
                 echo -e "\tFile already exists"
         else
-                eval wget ${WGET_OPTS} -nv "${DL_URL}" -O "${DEST_DIR}/${PACKAGE}"
+                eval ${DOWNLOADER} ${DL_OPTS} "${DL_URL}" ${DL_OUT} "${DEST_DIR}/${PACKAGE}"
                 if  [ ! -f "${DEST_DIR}/${PACKAGE}" ]; then
                         let "ERR+=1"
                 else
